# Generated by Django 2.2.2 on 2019-07-03 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noyeau', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InfoPost',
            new_name='IdClient',
        ),
    ]
