# Generated by Django 2.2.2 on 2019-07-05 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noyeau', '0003_auto_20190705_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idclient',
            name='telephone',
        ),
    ]
